#!/usr/bin/env bash
# Script that sets up a port

NGINX_CONFIG="/etc/nginx/sites-enabled/default"

sed -i -E 's/listen 8080 default_server;/listen 80 default_server;/' "$NGINX_CONFIG"
sed -i -E 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/' "$NGINX_CONFIG"
sed -i -E 's/ ipv6only=on//' "$NGINX_CONFIG"
service nginx restart
